# Generated by Django 3.0.4 on 2020-04-28 00:38

from django.db import migrations, models
import personal.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrosel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_name', models.CharField(max_length=32, verbose_name='Nome da Imagem')),
                ('imagem', models.ImageField(upload_to=personal.models.local_upload, verbose_name='Imagem do Produto')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': '(02) - Imagens',
            },
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(upload_to=personal.models.local_upload, verbose_name='Imagem do Produto'),
        ),
    ]
